#!/bin/bash

### BEGIN INIT INFO
# Provides:          ogn-pi
# Required-Start:    $all
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Wrapper to manage the OGN Pi process
# Description:       Wrapper to ensure that the OGN Pi process
#                    is run at all times, restarting as required
### END INIT INFO

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:$PATH

while true; do
  screen ogn-pi-wrapper.sh
  echo ""
  echo "Completed, restarting"
  echo ""
  sleep 2
done
